import json
import argparse
from pathlib import Path
from collections import Counter

def generate_executive_report(metrics_json: Path, output_md: Path) -> None:
    """Summarize SOC metrics into an executive-level Markdown briefing."""
    print(f"[+] Loading metrics payload: {metrics_json}\n")

    try:
        with open(metrics_json, "r", encoding="utf-8") as f:
            data = json.load(f)

        period = data.get("report_period", "Current Reporting Cycle")
        total_alerts = data.get("total_alerts_ingested", 0)
        resolved_incidents = data.get("resolved_incidents", 0)
        open_criticals = data.get("open_critical_vulnerabilities", 0)
        categories = Counter(data.get("incident_categories", {}))

        report_content = (
            f"# Executive Security Briefing\n"
            f"**Reporting Period:** {period}\n\n"
            f"## Core KPI Summary\n"
            f"- **Total Security Events Ingested:** `{total_alerts:,}`\n"
            f"- **Incidents Resolved by SOC:** `{resolved_incidents:,}`\n"
            f"- **Open Critical Vulnerabilities:** `{open_criticals}`\n\n"
            f"## Top Threat Vector Categories\n"
        )

        for category, count in categories.most_common(5):
            report_content += f"- **{category}:** {count} event(s)\n"

        report_content += "\n---\n*Report auto-generated by Security Engineering Operations Pipeline.*\n"

        with open(output_md, "w", encoding="utf-8") as out:
            out.write(report_content)

        print(f"[+] Executive report successfully generated at: {output_md}")

    except FileNotFoundError:
        print(f"[-] Error: File '{metrics_json}' not found.")
    except Exception as e:
        print(f"[-] Failed to generate executive report: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate executive Markdown security summary from raw SOC metrics")
    parser.add_argument("-m", "--metrics", required=True, type=Path, help="Path to raw metrics JSON")
    parser.add_argument("-o", "--output", default=Path("executive_briefing.md"), type=Path, help="Output Markdown report path")

    args = parser.parse_args()
    generate_executive_report(args.metrics, args.output)